export const env = {
    FIREBASE_APIKEY:                import.meta.env.VITE_FIREBASE_APIKEY,
    FIREBASE_AUTHDOMAIN:            import.meta.env.VITE_FIREBASE_AUTHDOMAIN,
    FIREBASE_PROJECTID:             import.meta.env.VITE_FIREBASE_PROJECTID,
    FIREBASE_STORAGEBUCKET:         import.meta.env.VITE_FIREBASE_STORAGEBUCKET,
    FIREBASE_MESSAGINGSENDERID:     import.meta.env.VITE_FIREBASE_MESSAGINGSENDERID,
    FIREBASE_APPID:                 import.meta.env.VITE_FIREBASE_APPID,
    CLOUDINARY_CLOUDNAME:           import.meta.env.VITE_CLOUDINARY_CLOUDNAME,
    CLOUDINARY_RESOURCE_TYPE:       import.meta.env.VITE_CLOUDINARY_RESOURCE_TYPE,
    CLOUDINARY_UPLOAD_PRESET:       import.meta.env.VITE_CLOUDINARY_UPLOAD_PRESET,
};
